version: '3'

services:

  redis:
    image: redis
    ports:
    - "6379:6379"
    command: redis-server --appendonly yes

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/drf_redis
    ports:
      - "8000:8000"
    depends_on:
      - redis